from pathlib import Path

import numpy as np

# 项目路径
PROJECT_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_DIR / "data"
INPUT_DIR = DATA_DIR / "input"
PROCESSED_DIR = DATA_DIR / "processed"
RESULTS_DIR = PROJECT_DIR / "results"
RESULTS_DATA_DIR = RESULTS_DIR / "data"
FIGURES_DIR = RESULTS_DIR / "figures"

# 天空模型：128×
# 128、2 角秒视场可覆盖当前约 5.34 Mlambda 的最大空间频率
IMAGE_SIZE = 128
FIELD_OF_VIEW_DEG = 2.0 / 3600.0
SKY_IMAGE_PATH = INPUT_DIR / "sky.png" # 
SKY_MODEL_PATH = PROCESSED_DIR / "sky_model.npz"
SKY_PREVIEW_PATH = PROCESSED_DIR / "sky_brightness.png"

# ALMA 尺度的理想化 Y 型阵列
ARRAY_NAME = "ALMA-inspired Y array"
NUMBER_OF_ANTENNAS = 50
ANTENNA_DIAMETER_M = 12.0
MINIMUM_SPACING_M = 15.0
MAXIMUM_BASELINE_M = 4000.0
Y_ARM_ANGLES_DEG = np.array([0.0, 120.0, 240.0])
ANTENNAS_PER_ARM = 16
Y_ARM_INNER_RADIUS_M = 35.0
Y_ARM_OUTER_RADIUS_M = MAXIMUM_BASELINE_M / np.sqrt(3.0)

# ALMA 台址与观测参数
OBSERVATORY_LATITUDE_DEG = -23.029
SPEED_OF_LIGHT_M_S = 299792458.0
OBSERVING_FREQUENCY_HZ = 100.0e9
SOURCE_DECLINATION_DEG = -30.0
HOUR_ANGLE_START_HOUR = -4.0
HOUR_ANGLE_END_HOUR = 4.0
TIME_INTERVAL_MIN = 5.0

# 直接非均匀 DFT 参数；设为 None 可计算全部 UV 点
VISIBILITY_BATCH_SIZE = 128
VISIBILITY_SAMPLE_LIMIT = 6000 # 采样上限，用多少个点做重建
RECONSTRUCTION_BATCH_SIZE = 256

# Hogbom CLEAN 参数
CLEAN_GAIN = 0.1
CLEAN_THRESHOLD_FRACTION = 0.01
CLEAN_MAX_ITERATIONS = 1000
CLEAN_POSITIVE_ONLY = True

# 输出路径
ARRAY_LAYOUT_FIGURE_PATH = FIGURES_DIR / "alma_y_array_layout.png"
UV_COVERAGE_FIGURE_PATH = FIGURES_DIR / "uv_coverage.png"
VISIBILITY_RESULTS_FIGURE_PATH = FIGURES_DIR / "visibility_results.png"
RECONSTRUCTION_FIGURE_PATH = FIGURES_DIR / "reconstruction_comparison.png"
UV_SAMPLES_DATA_PATH = RESULTS_DATA_DIR / "uv_samples.npz"
VISIBILITIES_DATA_PATH = RESULTS_DATA_DIR / "visibilities.npz"
RECONSTRUCTION_DATA_PATH = RESULTS_DATA_DIR / "reconstruction.npz"
